server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
    session:
      cookie:
        secure: true
        http-only: true
        same-site: none
        max-age: 360000000
      timeout: 360000000

spring:
  batch:
    job:
      enabled: false

springdoc:
  packages-to-scan: cholog
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api/swagger-docs
    groups:
      enabled: true
  cache:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    sessions:
      enabled: true
