name: CI/CD workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
      - feat/cicd-yml

jobs:
  build:
    runs-on: [ self-hosted ]

    defaults:
      run:
        shell: bash

    steps:
      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build

      - name: copy jar to EC2
        run: |
          scp -i ${{ secrets.EC2_PRIVATE_KEY }} -P ${{ secrets.EC2_PORT }} build/libs/wiseshop.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/wise-shop/back-end/tmp

      - name: SSH로 EC2에 접속하기
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            rm -rf /wise-shop/back-end/current
            mkdir /wise-shop/back-end/current 
            mv /wise-shop/back-end/tmp/wiseshop.jar /wise-shop/back-end/current/wiseshop.jar
            cd /wise-shop/back-end/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar wiseshop.jar > ./output.log 2>&1 &
            rm -rf /wise-shop/back-end/tmp
          EOF
