name: CI/CD workflow

on:
  push:
    branches:
      - main
      - feat/cicd-yml

jobs:
  build:
    runs-on: [ self-hosted ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Check current working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build

      - name: Test
        run: pwd

      - name: Copy jar
        run: sudo cp build/libs/wiseshop.jar /home/ubuntu/wise-shop

      - name: Stop running application
        run: |
          if pgrep -f "java -jar /home/ubuntu/wise-shop/wiseshop.jar"; then
            echo "Stopping existing application..."
            pkill -f "java -jar /home/ubuntu/wise-shop/wiseshop.jar"
          else
            echo "No running application found."
          fi

      - name: Run application
        run: sudo nohup java -jar /home/ubuntu/wise-shop/wiseshop.jar &

