name: CI/CD workflow

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
      - feat/cicd-yml

jobs:
  build:
    runs-on: [ self-hosted ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Check current working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew -x build

      - name: Create directory on EC2
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo mkdir -p /home/ubuntu/wise-shop/back-end/tmp
          EOF


      - name: Copy JAR to EC2
        run: |
          pwd
          ls build
          ls build/libs
          scp -i private_key.pem -P ${{ secrets.EC2_PORT }} build/libs/wiseshop.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ubuntu/wise-shop/back-end/tmp


      - name: SSH로 EC2에 접속하기
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
            rm -rf /home/ubuntu/wise-shop/back-end/current
            mkdir /home/ubuntu/wise-shop/back-end/current 
            mv /home/ubuntu/wise-shop/back-end/tmp/wiseshop.jar /home/ubuntu/wise-shop/back-end/current/wiseshop.jar
            cd /home/ubuntu/wise-shop/back-end/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar wiseshop.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/wise-shop/back-end/tmp
          EOF
