name: CI/CD workflow

on:
  push:
    branches:
      - main
      - build/alert-build

jobs:
  build:
    runs-on: [ self-hosted ]

    defaults:
      run:
        shell: bash

    steps:
      - name: Check current working directory
        run: pwd

      - name: List files
        run: ls -la

      - name: CheckOut
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set Up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and test
        id: build
        run: ./gradlew build

      - name: Test
        run: pwd

      - name: Copy jar
        run: sudo cp build/libs/wiseshop.jar /home/ubuntu/wise-shop

      - name: Stop running application
        run: |
          if pgrep -f "java -jar /home/ubuntu/wise-shop/wiseshop.jar"; then
            echo "Stopping existing application..."
            pkill -f "java -jar /home/ubuntu/wise-shop/wiseshop.jar"
          else
            echo "No running application found."
          fi

      - name: Run application
        run: sudo nohup java -jar /home/ubuntu/wise-shop/wiseshop.jar > /home/ubuntu/application.log 2>&1 &

      - name: Discord notification on success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "✅ 빌드 성공"
          description: "빌드가 성공적으로 수행되었습니다"
          color: 0x2ecc71
          username: GitHub Actions

      - name: Discord notification on failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "❌ 빌드 실패"
          description: "빌드가 실패했습니다 원인을 확인해주세요"
          color: 0xe74c3c
          username: GitHub Actions
